import { Montserrat } from "next/font/google";
import "./globals.css";
import { unstable_ViewTransition as ViewTransition } from 'react'

const montserrat = Montserrat({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransition>
      <html lang="en">
        <body
          className={`${montserrat.className} antialiased block m-0 p-0 font-normal text-base leading-none rounded-none outline-none cursor-auto text-white`}
        >
          {children}
        </body>
      </html>
    </ViewTransition>
  );
}
